import "../styles/globals.css";
import styles from "../styles/Home.module.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Link from "next/link";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.links}>
          <Link href="/client-side-rendering">Client-side rendering</Link>
          <Link href="/server-side-rendering">Server-side rendering</Link>
          <Link href="/static-site-generation">Static site generation</Link>
          <Link href="/incremental-static-generation">
            Incremental static generation
          </Link>
        </div>
      </header>
      <main className={styles.main}>
        <Component {...pageProps} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export default MyApp;
